In [1]:
import cv2
from PIL.Image import fromarray
import numpy as np
import scipy as sp
from skimage.feature import peak_local_max
from skimage.morphology import local_minima, local_maxima

In [2]:
img = cv2.imread('DATA/input.jpg', 0)

In [6]:
mx1 = local_maxima(img)
mn1 = local_minima(img)

In [41]:
l1 = len(img[mx1])
l2 = len(img[mn1])
s1 = np.sum(img[mx1])
s2 = np.sum(img[mn1])

In [51]:
peak_local_max(img)

array([[583, 758],
       [ 92, 473],
       [ 92, 472],
       ...,
       [591, 359],
       [592, 358],
       [595, 360]], dtype=int64)

In [52]:

local_maxima(img, indices=True)

(array([  0,   0,   0, ..., 596, 596, 596], dtype=int64),
 array([  0,   5,   9, ..., 938, 942, 943], dtype=int64))

In [3]:
fp = sp.ndimage.generate_binary_structure(2,2)
img[sp.ndimage.maximum_filter(img, footprint=fp) == img]

array([228, 230, 229, ..., 135, 149, 149], dtype=uint8)

In [62]:
lx = local_maxima(img, indices=True)
ly = np.array([[lx[0][i], lx[1][i]] for i in range(len(lx[0]))])

In [73]:
img.min()

0